let list = [
  {
    _id: 1,
    title: '반지',
    img: 'image1.jpg',
    price: '500',
    category: 'top',
    discount: '2',
  },
  {
    _id: 2,
    title: '하트귀걸이',
    img: 'image2.jpg',
    price: '1000',
    category: 'top',
    discount: '5',
  },
  {
    _id: 3,
    title: '14k 5개세트 심플 시리즈',
    img: 'image3.jpg',
    price: '5000',
    category: 'top',
    discount: '10',
  },
  {
    _id: 4,
    title: '14k/더블링 목걸이',
    img: 'image4.jpg',
    price: '150000',
    category: 'new',
    discount: '30',
  },
  {
    _id: 5,
    title: '14k 파라오의 목걸이',
    img: 'image5.jpg',
    price: '1500',
    category: 'new',
    discount: '0',
  },
  {
    _id: 6,
    title: '18k 심플목걸이',
    img: 'image6.jpg',
    price: '500000',
    category: 'new',
    discount: '20',
  },
  {
    _id: 7,
    title: '진주를 머금은 비녀 3세트',
    img: 'image7.jpg',
    price: '3000',
    category: 'new',
    discount: '0',
  },
  {
    _id: 8,
    title: '레이피어 머리핀 4세트',
    img: 'image8.jpg',
    price: '4000',
    category: 'new',
    discount: '10',
  },
  {
    _id: 9,
    title: '앙리마티스 사각목걸이',
    img: 'image9.jpg',
    price: '100000',
    category: 'new',
    discount: '10',
  },
  {
    _id: 10,
    title: '헤어핀',
    img: 'image10.jpg',
    price: '8000',
    category: 'top',
    discount: '10',
  },
];
export default list;
